# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' CohortRequest Class
#'
#' @field CohortData 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CohortRequest <- R6::R6Class(
  'CohortRequest',
  public = list(
    `CohortData` = NULL,
    initialize = function(`CohortData`){
      if (!missing(`CohortData`)) {
        stopifnot(R6::is.R6(`CohortData`))
        self$`CohortData` <- `CohortData`
      }
    },
    toJSON = function() {
      CohortRequestObject <- list()
      if (!is.null(self$`CohortData`)) {
        CohortRequestObject[['CohortData']] <- self$`CohortData`$toJSON()
      }

      CohortRequestObject
    },
    fromJSON = function(CohortRequestJson) {
      CohortRequestObject <- jsonlite::fromJSON(CohortRequestJson)
      if (!is.null(CohortRequestObject$`CohortData`)) {
        CohortDataObject <- CohortData$new()
        CohortDataObject$fromJSON(jsonlite::toJSON(CohortRequestObject$CohortData, auto_unbox = TRUE))
        self$`CohortData` <- CohortDataObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "CohortData": %s
        }',
        self$`CohortData`$toJSON()
      )
    },
    fromJSONString = function(CohortRequestJson) {
      CohortRequestObject <- jsonlite::fromJSON(CohortRequestJson)
      CohortDataObject <- CohortData$new()
      self$`CohortData` <- CohortDataObject$fromJSON(jsonlite::toJSON(CohortRequestObject$CohortData, auto_unbox = TRUE))
    }
  )
)
