# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Error Class
#'
#' @field code 
#' @field message 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Error <- R6::R6Class(
  'Error',
  public = list(
    `code` = NULL,
    `message` = NULL,
    initialize = function(`code`, `message`){
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      ErrorObject <- list()
      if (!is.null(self$`code`)) {
        ErrorObject[['code']] <- self$`code`
      }
      if (!is.null(self$`message`)) {
        ErrorObject[['message']] <- self$`message`
      }

      ErrorObject
    },
    fromJSON = function(ErrorJson) {
      ErrorObject <- jsonlite::fromJSON(ErrorJson)
      if (!is.null(ErrorObject$`code`)) {
        self$`code` <- ErrorObject$`code`
      }
      if (!is.null(ErrorObject$`message`)) {
        self$`message` <- ErrorObject$`message`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "code": %s,
           "message": %s
        }',
        self$`code`,
        self$`message`
      )
    },
    fromJSONString = function(ErrorJson) {
      ErrorObject <- jsonlite::fromJSON(ErrorJson)
      self$`code` <- ErrorObject$`code`
      self$`message` <- ErrorObject$`message`
    }
  )
)
