# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Genotype Class
#'
#' @field genotypeString 
#' @field genotypingMethods GenotypingMethods
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Genotype <- R6::R6Class(
  'Genotype',
  public = list(
    `genotypeString` = NULL,
    `genotypingMethods` = NULL,
    initialize = function(`genotypeString`, `genotypingMethods`){
      if (!missing(`genotypeString`)) {
        stopifnot(is.character(`genotypeString`), length(`genotypeString`) == 1)
        self$`genotypeString` <- `genotypeString`
      }
      if (!missing(`genotypingMethods`)) {
        stopifnot(is.list(`genotypingMethods`), length(`genotypingMethods`) != 0)
        lapply(`genotypingMethods`, function(x) stopifnot(R6::is.R6(x)))
        self$`genotypingMethods` <- `genotypingMethods`
      }
    },
    toJSON = function() {
      GenotypeObject <- list()
      if (!is.null(self$`genotypeString`)) {
        GenotypeObject[['genotypeString']] <- self$`genotypeString`
      }
      if (!is.null(self$`genotypingMethods`)) {
        GenotypeObject[['genotypingMethods']] <- lapply(self$`genotypingMethods`, function(x) x$toJSON())
      }

      GenotypeObject
    },
    fromJSON = function(GenotypeJson) {
      GenotypeObject <- jsonlite::fromJSON(GenotypeJson)
      if (!is.null(GenotypeObject$`genotypeString`)) {
        self$`genotypeString` <- GenotypeObject$`genotypeString`
      }
      if (!is.null(GenotypeObject$`genotypingMethods`)) {
        self$`genotypingMethods` <- lapply(GenotypeObject$`genotypingMethods`, function(x) {
          genotypingMethodsObject <- GenotypeMethod$new()
          genotypingMethodsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          genotypingMethodsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "genotypeString": %s,
           "genotypingMethods": [%s]
        }',
        self$`genotypeString`,
        lapply(self$`genotypingMethods`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GenotypeJson) {
      GenotypeObject <- jsonlite::fromJSON(GenotypeJson)
      self$`genotypeString` <- GenotypeObject$`genotypeString`
      self$`genotypingMethods` <- lapply(GenotypeObject$`genotypingMethods`, function(x) GenotypeMethod$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
