# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' HaplotypeFrequencyData Class
#'
#' @field License 
#' @field ResolutionData 
#' @field HaplotypeFrequencyList HaplotypeFrequencyList
#' @field QualityList 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HaplotypeFrequencyData <- R6::R6Class(
  'HaplotypeFrequencyData',
  public = list(
    `License` = NULL,
    `ResolutionData` = NULL,
    `HaplotypeFrequencyList` = NULL,
    `QualityList` = NULL,
    initialize = function(`License`, `ResolutionData`, `HaplotypeFrequencyList`, `QualityList`){
      if (!missing(`License`)) {
        stopifnot(R6::is.R6(`License`))
        self$`License` <- `License`
      }
      if (!missing(`ResolutionData`)) {
        stopifnot(R6::is.R6(`ResolutionData`))
        self$`ResolutionData` <- `ResolutionData`
      }
      if (!missing(`HaplotypeFrequencyList`)) {
        stopifnot(is.list(`HaplotypeFrequencyList`), length(`HaplotypeFrequencyList`) != 0)
        lapply(`HaplotypeFrequencyList`, function(x) stopifnot(R6::is.R6(x)))
        self$`HaplotypeFrequencyList` <- `HaplotypeFrequencyList`
      }
      if (!missing(`QualityList`)) {
        stopifnot(is.list(`QualityList`), length(`QualityList`) != 0)
        lapply(`QualityList`, function(x) stopifnot(R6::is.R6(x)))
        self$`QualityList` <- `QualityList`
      }
    },
    toJSON = function() {
      HaplotypeFrequencyDataObject <- list()
      if (!is.null(self$`License`)) {
        HaplotypeFrequencyDataObject[['License']] <- self$`License`$toJSON()
      }
      if (!is.null(self$`ResolutionData`)) {
        HaplotypeFrequencyDataObject[['ResolutionData']] <- self$`ResolutionData`$toJSON()
      }
      if (!is.null(self$`HaplotypeFrequencyList`)) {
        HaplotypeFrequencyDataObject[['HaplotypeFrequencyList']] <- lapply(self$`HaplotypeFrequencyList`, function(x) x$toJSON())
      }
      if (!is.null(self$`QualityList`)) {
        HaplotypeFrequencyDataObject[['QualityList']] <- lapply(self$`QualityList`, function(x) x$toJSON())
      }

      HaplotypeFrequencyDataObject
    },
    fromJSON = function(HaplotypeFrequencyDataJson) {
      HaplotypeFrequencyDataObject <- jsonlite::fromJSON(HaplotypeFrequencyDataJson)
      if (!is.null(HaplotypeFrequencyDataObject$`License`)) {
        LicenseObject <- License$new()
        LicenseObject$fromJSON(jsonlite::toJSON(HaplotypeFrequencyDataObject$License, auto_unbox = TRUE))
        self$`License` <- LicenseObject
      }
      if (!is.null(HaplotypeFrequencyDataObject$`ResolutionData`)) {
        ResolutionDataObject <- ResolutionData$new()
        ResolutionDataObject$fromJSON(jsonlite::toJSON(HaplotypeFrequencyDataObject$ResolutionData, auto_unbox = TRUE))
        self$`ResolutionData` <- ResolutionDataObject
      }
      if (!is.null(HaplotypeFrequencyDataObject$`HaplotypeFrequencyList`)) {
        self$`HaplotypeFrequencyList` <- lapply(HaplotypeFrequencyDataObject$`HaplotypeFrequencyList`, function(x) {
          HaplotypeFrequencyListObject <- HaplotypeFrequency$new()
          HaplotypeFrequencyListObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          HaplotypeFrequencyListObject
        })
      }
      if (!is.null(HaplotypeFrequencyDataObject$`QualityList`)) {
        self$`QualityList` <- lapply(HaplotypeFrequencyDataObject$`QualityList`, function(x) {
          QualityListObject <- Quality$new()
          QualityListObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          QualityListObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "License": %s,
           "ResolutionData": %s,
           "HaplotypeFrequencyList": [%s],
           "QualityList": [%s]
        }',
        self$`License`$toJSON(),
        self$`ResolutionData`$toJSON(),
        lapply(self$`HaplotypeFrequencyList`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`QualityList`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(HaplotypeFrequencyDataJson) {
      HaplotypeFrequencyDataObject <- jsonlite::fromJSON(HaplotypeFrequencyDataJson)
      LicenseObject <- License$new()
      self$`License` <- LicenseObject$fromJSON(jsonlite::toJSON(HaplotypeFrequencyDataObject$License, auto_unbox = TRUE))
      ResolutionDataObject <- ResolutionData$new()
      self$`ResolutionData` <- ResolutionDataObject$fromJSON(jsonlite::toJSON(HaplotypeFrequencyDataObject$ResolutionData, auto_unbox = TRUE))
      self$`HaplotypeFrequencyList` <- lapply(HaplotypeFrequencyDataObject$`HaplotypeFrequencyList`, function(x) HaplotypeFrequency$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`QualityList` <- lapply(HaplotypeFrequencyDataObject$`QualityList`, function(x) Quality$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
