# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' HFCurationListResponse Class
#'
#' @field HFCurationResponses 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HFCurationListResponse <- R6::R6Class(
  'HFCurationListResponse',
  public = list(
    `HFCurationResponses` = NULL,
    initialize = function(`HFCurationResponses`){
      if (!missing(`HFCurationResponses`)) {
        stopifnot(is.list(`HFCurationResponses`), length(`HFCurationResponses`) != 0)
        lapply(`HFCurationResponses`, function(x) stopifnot(R6::is.R6(x)))
        self$`HFCurationResponses` <- `HFCurationResponses`
      }
    },
    toJSON = function() {
      HFCurationListResponseObject <- list()
      if (!is.null(self$`HFCurationResponses`)) {
        HFCurationListResponseObject[['HFCurationResponses']] <- lapply(self$`HFCurationResponses`, function(x) x$toJSON())
      }

      HFCurationListResponseObject
    },
    fromJSON = function(HFCurationListResponseJson) {
      HFCurationListResponseObject <- jsonlite::fromJSON(HFCurationListResponseJson)
      if (!is.null(HFCurationListResponseObject$`HFCurationResponses`)) {
        self$`HFCurationResponses` <- lapply(HFCurationListResponseObject$`HFCurationResponses`, function(x) {
          HFCurationResponsesObject <- HFCurationResponse$new()
          HFCurationResponsesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          HFCurationResponsesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "HFCurationResponses": [%s]
        }',
        lapply(self$`HFCurationResponses`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(HFCurationListResponseJson) {
      HFCurationListResponseObject <- jsonlite::fromJSON(HFCurationListResponseJson)
      self$`HFCurationResponses` <- lapply(HFCurationListResponseObject$`HFCurationResponses`, function(x) HFCurationResponse$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
