# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' HFCurationResponse Class
#'
#' @field SubmissionID 
#' @field PopulationID 
#' @field CohortID 
#' @field MethodSetID 
#' @field LabelID 
#' @field HaplotypeListID 
#' @field ScopeID 
#' @field AccessID 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HFCurationResponse <- R6::R6Class(
  'HFCurationResponse',
  public = list(
    `SubmissionID` = NULL,
    `PopulationID` = NULL,
    `CohortID` = NULL,
    `MethodSetID` = NULL,
    `LabelID` = NULL,
    `HaplotypeListID` = NULL,
    `ScopeID` = NULL,
    `AccessID` = NULL,
    initialize = function(`SubmissionID`, `PopulationID`, `CohortID`, `MethodSetID`, `LabelID`, `HaplotypeListID`, `ScopeID`, `AccessID`){
      if (!missing(`SubmissionID`)) {
        stopifnot(is.numeric(`SubmissionID`), length(`SubmissionID`) == 1)
        self$`SubmissionID` <- `SubmissionID`
      }
      if (!missing(`PopulationID`)) {
        stopifnot(is.numeric(`PopulationID`), length(`PopulationID`) == 1)
        self$`PopulationID` <- `PopulationID`
      }
      if (!missing(`CohortID`)) {
        stopifnot(is.numeric(`CohortID`), length(`CohortID`) == 1)
        self$`CohortID` <- `CohortID`
      }
      if (!missing(`MethodSetID`)) {
        stopifnot(is.numeric(`MethodSetID`), length(`MethodSetID`) == 1)
        self$`MethodSetID` <- `MethodSetID`
      }
      if (!missing(`LabelID`)) {
        stopifnot(is.numeric(`LabelID`), length(`LabelID`) == 1)
        self$`LabelID` <- `LabelID`
      }
      if (!missing(`HaplotypeListID`)) {
        stopifnot(is.numeric(`HaplotypeListID`), length(`HaplotypeListID`) == 1)
        self$`HaplotypeListID` <- `HaplotypeListID`
      }
      if (!missing(`ScopeID`)) {
        stopifnot(is.numeric(`ScopeID`), length(`ScopeID`) == 1)
        self$`ScopeID` <- `ScopeID`
      }
      if (!missing(`AccessID`)) {
        stopifnot(is.numeric(`AccessID`), length(`AccessID`) == 1)
        self$`AccessID` <- `AccessID`
      }
    },
    toJSON = function() {
      HFCurationResponseObject <- list()
      if (!is.null(self$`SubmissionID`)) {
        HFCurationResponseObject[['SubmissionID']] <- self$`SubmissionID`
      }
      if (!is.null(self$`PopulationID`)) {
        HFCurationResponseObject[['PopulationID']] <- self$`PopulationID`
      }
      if (!is.null(self$`CohortID`)) {
        HFCurationResponseObject[['CohortID']] <- self$`CohortID`
      }
      if (!is.null(self$`MethodSetID`)) {
        HFCurationResponseObject[['MethodSetID']] <- self$`MethodSetID`
      }
      if (!is.null(self$`LabelID`)) {
        HFCurationResponseObject[['LabelID']] <- self$`LabelID`
      }
      if (!is.null(self$`HaplotypeListID`)) {
        HFCurationResponseObject[['HaplotypeListID']] <- self$`HaplotypeListID`
      }
      if (!is.null(self$`ScopeID`)) {
        HFCurationResponseObject[['ScopeID']] <- self$`ScopeID`
      }
      if (!is.null(self$`AccessID`)) {
        HFCurationResponseObject[['AccessID']] <- self$`AccessID`
      }

      HFCurationResponseObject
    },
    fromJSON = function(HFCurationResponseJson) {
      HFCurationResponseObject <- jsonlite::fromJSON(HFCurationResponseJson)
      if (!is.null(HFCurationResponseObject$`SubmissionID`)) {
        self$`SubmissionID` <- HFCurationResponseObject$`SubmissionID`
      }
      if (!is.null(HFCurationResponseObject$`PopulationID`)) {
        self$`PopulationID` <- HFCurationResponseObject$`PopulationID`
      }
      if (!is.null(HFCurationResponseObject$`CohortID`)) {
        self$`CohortID` <- HFCurationResponseObject$`CohortID`
      }
      if (!is.null(HFCurationResponseObject$`MethodSetID`)) {
        self$`MethodSetID` <- HFCurationResponseObject$`MethodSetID`
      }
      if (!is.null(HFCurationResponseObject$`LabelID`)) {
        self$`LabelID` <- HFCurationResponseObject$`LabelID`
      }
      if (!is.null(HFCurationResponseObject$`HaplotypeListID`)) {
        self$`HaplotypeListID` <- HFCurationResponseObject$`HaplotypeListID`
      }
      if (!is.null(HFCurationResponseObject$`ScopeID`)) {
        self$`ScopeID` <- HFCurationResponseObject$`ScopeID`
      }
      if (!is.null(HFCurationResponseObject$`AccessID`)) {
        self$`AccessID` <- HFCurationResponseObject$`AccessID`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "SubmissionID": %d,
           "PopulationID": %d,
           "CohortID": %d,
           "MethodSetID": %d,
           "LabelID": %d,
           "HaplotypeListID": %d,
           "ScopeID": %d,
           "AccessID": %d
        }',
        self$`SubmissionID`,
        self$`PopulationID`,
        self$`CohortID`,
        self$`MethodSetID`,
        self$`LabelID`,
        self$`HaplotypeListID`,
        self$`ScopeID`,
        self$`AccessID`
      )
    },
    fromJSONString = function(HFCurationResponseJson) {
      HFCurationResponseObject <- jsonlite::fromJSON(HFCurationResponseJson)
      self$`SubmissionID` <- HFCurationResponseObject$`SubmissionID`
      self$`PopulationID` <- HFCurationResponseObject$`PopulationID`
      self$`CohortID` <- HFCurationResponseObject$`CohortID`
      self$`MethodSetID` <- HFCurationResponseObject$`MethodSetID`
      self$`LabelID` <- HFCurationResponseObject$`LabelID`
      self$`HaplotypeListID` <- HFCurationResponseObject$`HaplotypeListID`
      self$`ScopeID` <- HFCurationResponseObject$`ScopeID`
      self$`AccessID` <- HFCurationResponseObject$`AccessID`
    }
  )
)
