# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' HFCurationRequest Class
#'
#' @field PopulationID 
#' @field CohortID 
#' @field MethodSetID 
#' @field MethodData 
#' @field LabelID 
#' @field LabelData 
#' @field HaplotypeFrequencyDataID 
#' @field HaplotypeFrequencyData 
#' @field ScopeID 
#' @field ScopeData 
#' @field AccessID 
#' @field AccessData 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HFCurationRequest <- R6::R6Class(
  'HFCurationRequest',
  public = list(
    `PopulationID` = NULL,
    `CohortID` = NULL,
    `MethodSetID` = NULL,
    `MethodData` = NULL,
    `LabelID` = NULL,
    `LabelData` = NULL,
    `HaplotypeFrequencyDataID` = NULL,
    `HaplotypeFrequencyData` = NULL,
    `ScopeID` = NULL,
    `ScopeData` = NULL,
    `AccessID` = NULL,
    `AccessData` = NULL,
    initialize = function(`PopulationID`, `CohortID`, `MethodSetID`, `MethodData`, `LabelID`, `LabelData`, `HaplotypeFrequencyDataID`, `HaplotypeFrequencyData`, `ScopeID`, `ScopeData`, `AccessID`, `AccessData`){
      if (!missing(`PopulationID`)) {
        stopifnot(is.numeric(`PopulationID`), length(`PopulationID`) == 1)
        self$`PopulationID` <- `PopulationID`
      }
      if (!missing(`CohortID`)) {
        stopifnot(is.numeric(`CohortID`), length(`CohortID`) == 1)
        self$`CohortID` <- `CohortID`
      }
      if (!missing(`MethodSetID`)) {
        stopifnot(is.numeric(`MethodSetID`), length(`MethodSetID`) == 1)
        self$`MethodSetID` <- `MethodSetID`
      }
      if (!missing(`MethodData`)) {
        stopifnot(R6::is.R6(`MethodData`))
        self$`MethodData` <- `MethodData`
      }
      if (!missing(`LabelID`)) {
        stopifnot(is.numeric(`LabelID`), length(`LabelID`) == 1)
        self$`LabelID` <- `LabelID`
      }
      if (!missing(`LabelData`)) {
        stopifnot(R6::is.R6(`LabelData`))
        self$`LabelData` <- `LabelData`
      }
      if (!missing(`HaplotypeFrequencyDataID`)) {
        stopifnot(is.character(`HaplotypeFrequencyDataID`), length(`HaplotypeFrequencyDataID`) == 1)
        self$`HaplotypeFrequencyDataID` <- `HaplotypeFrequencyDataID`
      }
      if (!missing(`HaplotypeFrequencyData`)) {
        stopifnot(R6::is.R6(`HaplotypeFrequencyData`))
        self$`HaplotypeFrequencyData` <- `HaplotypeFrequencyData`
      }
      if (!missing(`ScopeID`)) {
        stopifnot(is.numeric(`ScopeID`), length(`ScopeID`) == 1)
        self$`ScopeID` <- `ScopeID`
      }
      if (!missing(`ScopeData`)) {
        stopifnot(R6::is.R6(`ScopeData`))
        self$`ScopeData` <- `ScopeData`
      }
      if (!missing(`AccessID`)) {
        stopifnot(is.numeric(`AccessID`), length(`AccessID`) == 1)
        self$`AccessID` <- `AccessID`
      }
      if (!missing(`AccessData`)) {
        stopifnot(R6::is.R6(`AccessData`))
        self$`AccessData` <- `AccessData`
      }
    },
    toJSON = function() {
      HFCurationRequestObject <- list()
      if (!is.null(self$`PopulationID`)) {
        HFCurationRequestObject[['PopulationID']] <- self$`PopulationID`
      }
      if (!is.null(self$`CohortID`)) {
        HFCurationRequestObject[['CohortID']] <- self$`CohortID`
      }
      if (!is.null(self$`MethodSetID`)) {
        HFCurationRequestObject[['MethodSetID']] <- self$`MethodSetID`
      }
      if (!is.null(self$`MethodData`)) {
        HFCurationRequestObject[['MethodData']] <- self$`MethodData`$toJSON()
      }
      if (!is.null(self$`LabelID`)) {
        HFCurationRequestObject[['LabelID']] <- self$`LabelID`
      }
      if (!is.null(self$`LabelData`)) {
        HFCurationRequestObject[['LabelData']] <- self$`LabelData`$toJSON()
      }
      if (!is.null(self$`HaplotypeFrequencyDataID`)) {
        HFCurationRequestObject[['HaplotypeFrequencyDataID']] <- self$`HaplotypeFrequencyDataID`
      }
      if (!is.null(self$`HaplotypeFrequencyData`)) {
        HFCurationRequestObject[['HaplotypeFrequencyData']] <- self$`HaplotypeFrequencyData`$toJSON()
      }
      if (!is.null(self$`ScopeID`)) {
        HFCurationRequestObject[['ScopeID']] <- self$`ScopeID`
      }
      if (!is.null(self$`ScopeData`)) {
        HFCurationRequestObject[['ScopeData']] <- self$`ScopeData`$toJSON()
      }
      if (!is.null(self$`AccessID`)) {
        HFCurationRequestObject[['AccessID']] <- self$`AccessID`
      }
      if (!is.null(self$`AccessData`)) {
        HFCurationRequestObject[['AccessData']] <- self$`AccessData`$toJSON()
      }

      HFCurationRequestObject
    },
    fromJSON = function(HFCurationRequestJson) {
      HFCurationRequestObject <- jsonlite::fromJSON(HFCurationRequestJson)
      if (!is.null(HFCurationRequestObject$`PopulationID`)) {
        self$`PopulationID` <- HFCurationRequestObject$`PopulationID`
      }
      if (!is.null(HFCurationRequestObject$`CohortID`)) {
        self$`CohortID` <- HFCurationRequestObject$`CohortID`
      }
      if (!is.null(HFCurationRequestObject$`MethodSetID`)) {
        self$`MethodSetID` <- HFCurationRequestObject$`MethodSetID`
      }
      if (!is.null(HFCurationRequestObject$`MethodData`)) {
        MethodDataObject <- MethodData$new()
        MethodDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$MethodData, auto_unbox = TRUE))
        self$`MethodData` <- MethodDataObject
      }
      if (!is.null(HFCurationRequestObject$`LabelID`)) {
        self$`LabelID` <- HFCurationRequestObject$`LabelID`
      }
      if (!is.null(HFCurationRequestObject$`LabelData`)) {
        LabelDataObject <- LabelData$new()
        LabelDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$LabelData, auto_unbox = TRUE))
        self$`LabelData` <- LabelDataObject
      }
      if (!is.null(HFCurationRequestObject$`HaplotypeFrequencyDataID`)) {
        self$`HaplotypeFrequencyDataID` <- HFCurationRequestObject$`HaplotypeFrequencyDataID`
      }
      if (!is.null(HFCurationRequestObject$`HaplotypeFrequencyData`)) {
        HaplotypeFrequencyDataObject <- HaplotypeFrequencyData$new()
        HaplotypeFrequencyDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$HaplotypeFrequencyData, auto_unbox = TRUE))
        self$`HaplotypeFrequencyData` <- HaplotypeFrequencyDataObject
      }
      if (!is.null(HFCurationRequestObject$`ScopeID`)) {
        self$`ScopeID` <- HFCurationRequestObject$`ScopeID`
      }
      if (!is.null(HFCurationRequestObject$`ScopeData`)) {
        ScopeDataObject <- ScopeData$new()
        ScopeDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$ScopeData, auto_unbox = TRUE))
        self$`ScopeData` <- ScopeDataObject
      }
      if (!is.null(HFCurationRequestObject$`AccessID`)) {
        self$`AccessID` <- HFCurationRequestObject$`AccessID`
      }
      if (!is.null(HFCurationRequestObject$`AccessData`)) {
        AccessDataObject <- AccessData$new()
        AccessDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$AccessData, auto_unbox = TRUE))
        self$`AccessData` <- AccessDataObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "PopulationID": %d,
           "CohortID": %d,
           "MethodSetID": %d,
           "MethodData": %s,
           "LabelID": %d,
           "LabelData": %s,
           "HaplotypeFrequencyDataID": %s,
           "HaplotypeFrequencyData": %s,
           "ScopeID": %d,
           "ScopeData": %s,
           "AccessID": %d,
           "AccessData": %s
        }',
        self$`PopulationID`,
        self$`CohortID`,
        self$`MethodSetID`,
        self$`MethodData`$toJSON(),
        self$`LabelID`,
        self$`LabelData`$toJSON(),
        self$`HaplotypeFrequencyDataID`,
        self$`HaplotypeFrequencyData`$toJSON(),
        self$`ScopeID`,
        self$`ScopeData`$toJSON(),
        self$`AccessID`,
        self$`AccessData`$toJSON()
      )
    },
    fromJSONString = function(HFCurationRequestJson) {
      HFCurationRequestObject <- jsonlite::fromJSON(HFCurationRequestJson)
      self$`PopulationID` <- HFCurationRequestObject$`PopulationID`
      self$`CohortID` <- HFCurationRequestObject$`CohortID`
      self$`MethodSetID` <- HFCurationRequestObject$`MethodSetID`
      MethodDataObject <- MethodData$new()
      self$`MethodData` <- MethodDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$MethodData, auto_unbox = TRUE))
      self$`LabelID` <- HFCurationRequestObject$`LabelID`
      LabelDataObject <- LabelData$new()
      self$`LabelData` <- LabelDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$LabelData, auto_unbox = TRUE))
      self$`HaplotypeFrequencyDataID` <- HFCurationRequestObject$`HaplotypeFrequencyDataID`
      HaplotypeFrequencyDataObject <- HaplotypeFrequencyData$new()
      self$`HaplotypeFrequencyData` <- HaplotypeFrequencyDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$HaplotypeFrequencyData, auto_unbox = TRUE))
      self$`ScopeID` <- HFCurationRequestObject$`ScopeID`
      ScopeDataObject <- ScopeData$new()
      self$`ScopeData` <- ScopeDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$ScopeData, auto_unbox = TRUE))
      self$`AccessID` <- HFCurationRequestObject$`AccessID`
      AccessDataObject <- AccessData$new()
      self$`AccessData` <- AccessDataObject$fromJSON(jsonlite::toJSON(HFCurationRequestObject$AccessData, auto_unbox = TRUE))
    }
  )
)
