# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' LabelData Class
#'
#' @field LabelList 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LabelData <- R6::R6Class(
  'LabelData',
  public = list(
    `LabelList` = NULL,
    initialize = function(`LabelList`){
      if (!missing(`LabelList`)) {
        stopifnot(is.list(`LabelList`), length(`LabelList`) != 0)
        lapply(`LabelList`, function(x) stopifnot(R6::is.R6(x)))
        self$`LabelList` <- `LabelList`
      }
    },
    toJSON = function() {
      LabelDataObject <- list()
      if (!is.null(self$`LabelList`)) {
        LabelDataObject[['LabelList']] <- lapply(self$`LabelList`, function(x) x$toJSON())
      }

      LabelDataObject
    },
    fromJSON = function(LabelDataJson) {
      LabelDataObject <- jsonlite::fromJSON(LabelDataJson)
      if (!is.null(LabelDataObject$`LabelList`)) {
        self$`LabelList` <- lapply(LabelDataObject$`LabelList`, function(x) {
          LabelListObject <- Label$new()
          LabelListObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          LabelListObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "LabelList": [%s]
        }',
        lapply(self$`LabelList`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(LabelDataJson) {
      LabelDataObject <- jsonlite::fromJSON(LabelDataJson)
      self$`LabelList` <- lapply(LabelDataObject$`LabelList`, function(x) Label$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
