# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' LabelResponse Class
#'
#' @field LabelsList 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LabelResponse <- R6::R6Class(
  'LabelResponse',
  public = list(
    `LabelsList` = NULL,
    initialize = function(`LabelsList`){
      if (!missing(`LabelsList`)) {
        stopifnot(is.list(`LabelsList`), length(`LabelsList`) != 0)
        lapply(`LabelsList`, function(x) stopifnot(R6::is.R6(x)))
        self$`LabelsList` <- `LabelsList`
      }
    },
    toJSON = function() {
      LabelResponseObject <- list()
      if (!is.null(self$`LabelsList`)) {
        LabelResponseObject[['LabelsList']] <- lapply(self$`LabelsList`, function(x) x$toJSON())
      }

      LabelResponseObject
    },
    fromJSON = function(LabelResponseJson) {
      LabelResponseObject <- jsonlite::fromJSON(LabelResponseJson)
      if (!is.null(LabelResponseObject$`LabelsList`)) {
        self$`LabelsList` <- lapply(LabelResponseObject$`LabelsList`, function(x) {
          LabelsListObject <- LabelData$new()
          LabelsListObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          LabelsListObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "LabelsList": [%s]
        }',
        lapply(self$`LabelsList`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(LabelResponseJson) {
      LabelResponseObject <- jsonlite::fromJSON(LabelResponseJson)
      self$`LabelsList` <- lapply(LabelResponseObject$`LabelsList`, function(x) LabelData$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
