# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' License Class
#'
#' @field typeOfLicense 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
License <- R6::R6Class(
  'License',
  public = list(
    `typeOfLicense` = NULL,
    initialize = function(`typeOfLicense`){
      if (!missing(`typeOfLicense`)) {
        stopifnot(is.character(`typeOfLicense`), length(`typeOfLicense`) == 1)
        self$`typeOfLicense` <- `typeOfLicense`
      }
    },
    toJSON = function() {
      LicenseObject <- list()
      if (!is.null(self$`typeOfLicense`)) {
        LicenseObject[['typeOfLicense']] <- self$`typeOfLicense`
      }

      LicenseObject
    },
    fromJSON = function(LicenseJson) {
      LicenseObject <- jsonlite::fromJSON(LicenseJson)
      if (!is.null(LicenseObject$`typeOfLicense`)) {
        self$`typeOfLicense` <- LicenseObject$`typeOfLicense`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "typeOfLicense": %s
        }',
        self$`typeOfLicense`
      )
    },
    fromJSONString = function(LicenseJson) {
      LicenseObject <- jsonlite::fromJSON(LicenseJson)
      self$`typeOfLicense` <- LicenseObject$`typeOfLicense`
    }
  )
)
