# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MethodData Class
#'
#' @field MethodList Method
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MethodData <- R6::R6Class(
  'MethodData',
  public = list(
    `MethodList` = NULL,
    initialize = function(`MethodList`){
      if (!missing(`MethodList`)) {
        stopifnot(is.list(`MethodList`), length(`MethodList`) != 0)
        lapply(`MethodList`, function(x) stopifnot(R6::is.R6(x)))
        self$`MethodList` <- `MethodList`
      }
    },
    toJSON = function() {
      MethodDataObject <- list()
      if (!is.null(self$`MethodList`)) {
        MethodDataObject[['MethodList']] <- lapply(self$`MethodList`, function(x) x$toJSON())
      }

      MethodDataObject
    },
    fromJSON = function(MethodDataJson) {
      MethodDataObject <- jsonlite::fromJSON(MethodDataJson)
      if (!is.null(MethodDataObject$`MethodList`)) {
        self$`MethodList` <- lapply(MethodDataObject$`MethodList`, function(x) {
          MethodListObject <- Method$new()
          MethodListObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          MethodListObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "MethodList": [%s]
        }',
        lapply(self$`MethodList`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(MethodDataJson) {
      MethodDataObject <- jsonlite::fromJSON(MethodDataJson)
      self$`MethodList` <- lapply(MethodDataObject$`MethodList`, function(x) Method$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
