# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Method Class
#'
#' @field typeOfMethod 
#' @field methodValue 
#' @field methodComment 
#' @field methodReference 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Method <- R6::R6Class(
  'Method',
  public = list(
    `typeOfMethod` = NULL,
    `methodValue` = NULL,
    `methodComment` = NULL,
    `methodReference` = NULL,
    initialize = function(`typeOfMethod`, `methodValue`, `methodComment`, `methodReference`){
      if (!missing(`typeOfMethod`)) {
        stopifnot(is.character(`typeOfMethod`), length(`typeOfMethod`) == 1)
        self$`typeOfMethod` <- `typeOfMethod`
      }
      if (!missing(`methodValue`)) {
        stopifnot(is.character(`methodValue`), length(`methodValue`) == 1)
        self$`methodValue` <- `methodValue`
      }
      if (!missing(`methodComment`)) {
        stopifnot(is.character(`methodComment`), length(`methodComment`) == 1)
        self$`methodComment` <- `methodComment`
      }
      if (!missing(`methodReference`)) {
        stopifnot(is.character(`methodReference`), length(`methodReference`) == 1)
        self$`methodReference` <- `methodReference`
      }
    },
    toJSON = function() {
      MethodObject <- list()
      if (!is.null(self$`typeOfMethod`)) {
        MethodObject[['typeOfMethod']] <- self$`typeOfMethod`
      }
      if (!is.null(self$`methodValue`)) {
        MethodObject[['methodValue']] <- self$`methodValue`
      }
      if (!is.null(self$`methodComment`)) {
        MethodObject[['methodComment']] <- self$`methodComment`
      }
      if (!is.null(self$`methodReference`)) {
        MethodObject[['methodReference']] <- self$`methodReference`
      }

      MethodObject
    },
    fromJSON = function(MethodJson) {
      MethodObject <- jsonlite::fromJSON(MethodJson)
      if (!is.null(MethodObject$`typeOfMethod`)) {
        self$`typeOfMethod` <- MethodObject$`typeOfMethod`
      }
      if (!is.null(MethodObject$`methodValue`)) {
        self$`methodValue` <- MethodObject$`methodValue`
      }
      if (!is.null(MethodObject$`methodComment`)) {
        self$`methodComment` <- MethodObject$`methodComment`
      }
      if (!is.null(MethodObject$`methodReference`)) {
        self$`methodReference` <- MethodObject$`methodReference`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "typeOfMethod": %s,
           "methodValue": %s,
           "methodComment": %s,
           "methodReference": %s
        }',
        self$`typeOfMethod`,
        self$`methodValue`,
        self$`methodComment`,
        self$`methodReference`
      )
    },
    fromJSONString = function(MethodJson) {
      MethodObject <- jsonlite::fromJSON(MethodJson)
      self$`typeOfMethod` <- MethodObject$`typeOfMethod`
      self$`methodValue` <- MethodObject$`methodValue`
      self$`methodComment` <- MethodObject$`methodComment`
      self$`methodReference` <- MethodObject$`methodReference`
    }
  )
)
