# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PopulationResponse Class
#'
#' @field PopulationList 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PopulationResponse <- R6::R6Class(
  'PopulationResponse',
  public = list(
    `PopulationList` = NULL,
    initialize = function(`PopulationList`){
      if (!missing(`PopulationList`)) {
        stopifnot(is.list(`PopulationList`), length(`PopulationList`) != 0)
        lapply(`PopulationList`, function(x) stopifnot(R6::is.R6(x)))
        self$`PopulationList` <- `PopulationList`
      }
    },
    toJSON = function() {
      PopulationResponseObject <- list()
      if (!is.null(self$`PopulationList`)) {
        PopulationResponseObject[['PopulationList']] <- lapply(self$`PopulationList`, function(x) x$toJSON())
      }

      PopulationResponseObject
    },
    fromJSON = function(PopulationResponseJson) {
      PopulationResponseObject <- jsonlite::fromJSON(PopulationResponseJson)
      if (!is.null(PopulationResponseObject$`PopulationList`)) {
        self$`PopulationList` <- lapply(PopulationResponseObject$`PopulationList`, function(x) {
          PopulationListObject <- PopulationData$new()
          PopulationListObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          PopulationListObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "PopulationList": [%s]
        }',
        lapply(self$`PopulationList`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(PopulationResponseJson) {
      PopulationResponseObject <- jsonlite::fromJSON(PopulationResponseJson)
      self$`PopulationList` <- lapply(PopulationResponseObject$`PopulationList`, function(x) PopulationData$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
