# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PopulationData Class
#'
#' @field id id
#' @field name Name
#' @field description description
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PopulationData <- R6::R6Class(
  'PopulationData',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `description` = NULL,
    initialize = function(`id`, `name`, `description`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      PopulationDataObject <- list()
      if (!is.null(self$`id`)) {
        PopulationDataObject[['id']] <- self$`id`
      }
      if (!is.null(self$`name`)) {
        PopulationDataObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        PopulationDataObject[['description']] <- self$`description`
      }

      PopulationDataObject
    },
    fromJSON = function(PopulationDataJson) {
      PopulationDataObject <- jsonlite::fromJSON(PopulationDataJson)
      if (!is.null(PopulationDataObject$`id`)) {
        self$`id` <- PopulationDataObject$`id`
      }
      if (!is.null(PopulationDataObject$`name`)) {
        self$`name` <- PopulationDataObject$`name`
      }
      if (!is.null(PopulationDataObject$`description`)) {
        self$`description` <- PopulationDataObject$`description`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d,
           "name": %s,
           "description": %s
        }',
        self$`id`,
        self$`name`,
        self$`description`
      )
    },
    fromJSONString = function(PopulationDataJson) {
      PopulationDataObject <- jsonlite::fromJSON(PopulationDataJson)
      self$`id` <- PopulationDataObject$`id`
      self$`name` <- PopulationDataObject$`name`
      self$`description` <- PopulationDataObject$`description`
    }
  )
)
