# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PopulationRequest Class
#'
#' @field name 
#' @field description 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PopulationRequest <- R6::R6Class(
  'PopulationRequest',
  public = list(
    `name` = NULL,
    `description` = NULL,
    initialize = function(`name`, `description`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      PopulationRequestObject <- list()
      if (!is.null(self$`name`)) {
        PopulationRequestObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        PopulationRequestObject[['description']] <- self$`description`
      }

      PopulationRequestObject
    },
    fromJSON = function(PopulationRequestJson) {
      PopulationRequestObject <- jsonlite::fromJSON(PopulationRequestJson)
      if (!is.null(PopulationRequestObject$`name`)) {
        self$`name` <- PopulationRequestObject$`name`
      }
      if (!is.null(PopulationRequestObject$`description`)) {
        self$`description` <- PopulationRequestObject$`description`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s
        }',
        self$`name`,
        self$`description`
      )
    },
    fromJSONString = function(PopulationRequestJson) {
      PopulationRequestObject <- jsonlite::fromJSON(PopulationRequestJson)
      self$`name` <- PopulationRequestObject$`name`
      self$`description` <- PopulationRequestObject$`description`
    }
  )
)
