# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScopeElement Class
#'
#' @field name 
#' @field freeName 
#' @field typeOfScope 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScopeElement <- R6::R6Class(
  'ScopeElement',
  public = list(
    `name` = NULL,
    `freeName` = NULL,
    `typeOfScope` = NULL,
    initialize = function(`name`, `freeName`, `typeOfScope`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`freeName`)) {
        stopifnot(is.character(`freeName`), length(`freeName`) == 1)
        self$`freeName` <- `freeName`
      }
      if (!missing(`typeOfScope`)) {
        stopifnot(is.character(`typeOfScope`), length(`typeOfScope`) == 1)
        self$`typeOfScope` <- `typeOfScope`
      }
    },
    toJSON = function() {
      ScopeElementObject <- list()
      if (!is.null(self$`name`)) {
        ScopeElementObject[['name']] <- self$`name`
      }
      if (!is.null(self$`freeName`)) {
        ScopeElementObject[['freeName']] <- self$`freeName`
      }
      if (!is.null(self$`typeOfScope`)) {
        ScopeElementObject[['typeOfScope']] <- self$`typeOfScope`
      }

      ScopeElementObject
    },
    fromJSON = function(ScopeElementJson) {
      ScopeElementObject <- jsonlite::fromJSON(ScopeElementJson)
      if (!is.null(ScopeElementObject$`name`)) {
        self$`name` <- ScopeElementObject$`name`
      }
      if (!is.null(ScopeElementObject$`freeName`)) {
        self$`freeName` <- ScopeElementObject$`freeName`
      }
      if (!is.null(ScopeElementObject$`typeOfScope`)) {
        self$`typeOfScope` <- ScopeElementObject$`typeOfScope`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "freeName": %s,
           "typeOfScope": %s
        }',
        self$`name`,
        self$`freeName`,
        self$`typeOfScope`
      )
    },
    fromJSONString = function(ScopeElementJson) {
      ScopeElementObject <- jsonlite::fromJSON(ScopeElementJson)
      self$`name` <- ScopeElementObject$`name`
      self$`freeName` <- ScopeElementObject$`freeName`
      self$`typeOfScope` <- ScopeElementObject$`typeOfScope`
    }
  )
)
