# Haplotype Frequency Curation Service
#
# Allows to store and return haplotype frequency data
#
# OpenAPI spec version: 1.0.0
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ScopeData Class
#'
#' @field ScopeElement ScopeElement
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScopeData <- R6::R6Class(
  'ScopeData',
  public = list(
    `ScopeElement` = NULL,
    initialize = function(`ScopeElement`){
      if (!missing(`ScopeElement`)) {
        stopifnot(is.list(`ScopeElement`), length(`ScopeElement`) != 0)
        lapply(`ScopeElement`, function(x) stopifnot(R6::is.R6(x)))
        self$`ScopeElement` <- `ScopeElement`
      }
    },
    toJSON = function() {
      ScopeDataObject <- list()
      if (!is.null(self$`ScopeElement`)) {
        ScopeDataObject[['ScopeElement']] <- lapply(self$`ScopeElement`, function(x) x$toJSON())
      }

      ScopeDataObject
    },
    fromJSON = function(ScopeDataJson) {
      ScopeDataObject <- jsonlite::fromJSON(ScopeDataJson)
      if (!is.null(ScopeDataObject$`ScopeElement`)) {
        self$`ScopeElement` <- lapply(ScopeDataObject$`ScopeElement`, function(x) {
          ScopeElementObject <- ScopeElement$new()
          ScopeElementObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          ScopeElementObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "ScopeElement": [%s]
        }',
        lapply(self$`ScopeElement`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(ScopeDataJson) {
      ScopeDataObject <- jsonlite::fromJSON(ScopeDataJson)
      self$`ScopeElement` <- lapply(ScopeDataObject$`ScopeElement`, function(x) ScopeElement$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
