=begin comment

Haplotype Frequency Curation Service

Allows to store and return haplotype frequency data

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::Object::HFCurationResponse;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Haplotype Frequency Curation Service

Allows to store and return haplotype frequency data

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'HFCurationResponse',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'submission_id' => {
    	datatype => 'string',
    	base_name => 'SubmissionID',
    	description => 'Reference to a submission',
    	format => '',
    	read_only => '',
    		},
    'population_id' => {
    	datatype => 'string',
    	base_name => 'PopulationID',
    	description => 'Reference to a population',
    	format => '',
    	read_only => '',
    		},
    'cohort_id' => {
    	datatype => 'string',
    	base_name => 'CohortID',
    	description => 'References a cohort',
    	format => '',
    	read_only => '',
    		},
    'method_set_id' => {
    	datatype => 'string',
    	base_name => 'MethodSetID',
    	description => 'References a method set',
    	format => '',
    	read_only => '',
    		},
    'label_id' => {
    	datatype => 'string',
    	base_name => 'LabelID',
    	description => 'References a label',
    	format => '',
    	read_only => '',
    		},
    'haplotype_list_id' => {
    	datatype => 'string',
    	base_name => 'HaplotypeListID',
    	description => 'References a haplotype list',
    	format => '',
    	read_only => '',
    		},
    'scope_id' => {
    	datatype => 'string',
    	base_name => 'ScopeID',
    	description => 'References a scope',
    	format => '',
    	read_only => '',
    		},
    'access_id' => {
    	datatype => 'string',
    	base_name => 'AccessID',
    	description => 'References a access controls',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'submission_id' => 'string',
    'population_id' => 'string',
    'cohort_id' => 'string',
    'method_set_id' => 'string',
    'label_id' => 'string',
    'haplotype_list_id' => 'string',
    'scope_id' => 'string',
    'access_id' => 'string'
} );

__PACKAGE__->attribute_map( {
    'submission_id' => 'SubmissionID',
    'population_id' => 'PopulationID',
    'cohort_id' => 'CohortID',
    'method_set_id' => 'MethodSetID',
    'label_id' => 'LabelID',
    'haplotype_list_id' => 'HaplotypeListID',
    'scope_id' => 'ScopeID',
    'access_id' => 'AccessID'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
