/*
 * Haplotype Frequency Curation Service
 * Allows to store and return haplotype frequency data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Genotype;
import io.swagger.client.model.License;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * List of Genotypes
 */
@ApiModel(description = "List of Genotypes")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-01T08:14:07.511-07:00")
public class GenotypeList {
  @SerializedName("License")
  private License license = null;

  @SerializedName("Genotype")
  private List<Genotype> genotype = null;

  public GenotypeList license(License license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @ApiModelProperty(value = "")
  public License getLicense() {
    return license;
  }

  public void setLicense(License license) {
    this.license = license;
  }

  public GenotypeList genotype(List<Genotype> genotype) {
    this.genotype = genotype;
    return this;
  }

  public GenotypeList addGenotypeItem(Genotype genotypeItem) {
    if (this.genotype == null) {
      this.genotype = new ArrayList<Genotype>();
    }
    this.genotype.add(genotypeItem);
    return this;
  }

   /**
   * Additional Information on genotype
   * @return genotype
  **/
  @ApiModelProperty(value = "Additional Information on genotype")
  public List<Genotype> getGenotype() {
    return genotype;
  }

  public void setGenotype(List<Genotype> genotype) {
    this.genotype = genotype;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenotypeList genotypeList = (GenotypeList) o;
    return Objects.equals(this.license, genotypeList.license) &&
        Objects.equals(this.genotype, genotypeList.genotype);
  }

  @Override
  public int hashCode() {
    return Objects.hash(license, genotype);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenotypeList {\n");
    
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    genotype: ").append(toIndentedString(genotype)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

