/*
 * Haplotype Frequency Curation Service
 * Allows to store and return haplotype frequency data
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Method;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MethodList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-12T09:58:25.177-07:00")
public class MethodList {
  @SerializedName("Method")
  private List<Method> method = null;

  public MethodList method(List<Method> method) {
    this.method = method;
    return this;
  }

  public MethodList addMethodItem(Method methodItem) {
    if (this.method == null) {
      this.method = new ArrayList<Method>();
    }
    this.method.add(methodItem);
    return this;
  }

   /**
   * list of methods
   * @return method
  **/
  @ApiModelProperty(value = "list of methods")
  public List<Method> getMethod() {
    return method;
  }

  public void setMethod(List<Method> method) {
    this.method = method;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MethodList methodList = (MethodList) o;
    return Objects.equals(this.method, methodList.method);
  }

  @Override
  public int hashCode() {
    return Objects.hash(method);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MethodList {\n");
    
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

